<?php if (!defined('WPINC')) {
	die;
} return
'<?xml version="1.0" encoding="UTF-8"?>
<root>
	<columnName>ID</columnName>
	<columnName>name</columnName>
	<columnName>description</columnName>
	<columnName>descriptionShort</columnName>
	<columnName>descriptionLong</columnName>
	<columnName>price</columnName>
	<columnName>VAT</columnName>
	<columnName>currency</columnName>
	<columnName>productURL</columnName>
	<columnName>imageURL</columnName>
	<columnName>thumbnailURL</columnName>
	<columnName>imageURL_large</columnName>
	<columnName>imageURL_small</columnName>
	<columnName>categories</columnName>
	<columnName>subcategories</columnName>
	<columnName>subsubcategories</columnName>
	<columnName>categoryPath</columnName>
	<columnName>tags</columnName>
	<columnName>warranty</columnName>
	<columnName>EAN</columnName>
	<columnName>SKU</columnName>
	<columnName>ISBN</columnName>
	<columnName>UPC</columnName>
	<columnName>MPN</columnName>
	<columnName>GTIN</columnName>
	<columnName>categoryURL</columnName>
	<columnName>deliveryTime</columnName>
	<columnName>deliveryCosts</columnName>
	<columnName>stock</columnName>
	<columnName>availability</columnName>
	<columnName>manufacturer</columnName>
	<columnName>brand</columnName>
	<columnName>model</columnName>
	<columnName>color</columnName>
	<columnName>weight</columnName>
	<columnName>contents</columnName>
	<columnName>version</columnName>
	<columnName>size</columnName>
	<columnName>width</columnName>
	<columnName>height</columnName>
	<columnName>depth</columnName>
	<columnName>length</columnName>
	<columnName>fabric</columnName>
	<columnName>material</columnName>
	<columnName>condition</columnName>
	<columnName>extraInfo</columnName>
	<columnName>discount</columnName>
	<columnName>specialOffer</columnName>
	<columnName>setupFee</columnName>
	<columnName>newContract</columnName>
	<columnName>contractDuration</columnName>
	<columnName>contractType</columnName>
	<columnName>contractPrice</columnName>
	<columnName>contractDataBundle</columnName>
	<columnName>provider</columnName>
	<columnName>phoneName</columnName>
	<columnName>phonePrice</columnName>
	<columnName>contractMinutes</columnName>
	<columnName>contractSMS</columnName>
	<columnName>simlock</columnName>
	<columnName>continent</columnName>
	<columnName>country</columnName>
	<columnName>region</columnName>
	<columnName>province</columnName>
	<columnName>city</columnName>
	<columnName>address</columnName>
	<columnName>zipcode</columnName>
	<columnName>longitude</columnName>
	<columnName>latitude</columnName>
	<columnName>airport</columnName>
	<columnName>airline</columnName>
	<columnName>numberOfPersons</columnName>
	<columnName>minPersons</columnName>
	<columnName>maxPersons</columnName>
	<columnName>accommodationType</columnName>
	<columnName>transportType</columnName>
	<columnName>duration</columnName>
	<columnName>numberOfDays</columnName>
	<columnName>numberOfNights</columnName>
	<columnName>stars</columnName>
	<columnName>departureDate</columnName>
	<columnName>arrivalDate</columnName>
	<columnName>returnDate</columnName>
	<columnName>departurePrice</columnName>
	<columnName>fromPrice</columnName>
	<columnName>petsAllowed</columnName>
	<columnName>smokingAllowed</columnName>
	<columnName>additionalCosts</columnName>
	<columnName>iataDeparture</columnName>
	<columnName>iataArrival</columnName>
	<columnName>serviceType</columnName>
	<columnName>facilities</columnName>
	<columnName>countryISO</columnName>
	<columnName>countryURL</columnName>
	<columnName>cityURL</columnName>
	<columnName>regionURL</columnName>
	<columnName>accommodation</columnName>
	<columnName>gender</columnName>
	<columnName>rating</columnName>
</root>';
